language: node_js
node_js:
  - lts/*
sudo: required
cache: yarn

addons:
  apt:
    packages:
      - calibre
      - xvfb

before_install:
  - sudo ln -s ./ebook-convert-wrapper /usr/local/bin/ebook-convert
  - which ebook-convert
  - echo $PATH
  - ls -la /usr/local/bin

script: yarn build

after_success:
  - openssl aes-256-cbc -K $encrypted_f123d460b42a_key -iv $encrypted_f123d460b42a_iv -in deployment.key.enc -out deployment.key -d
  - rsync -avz --delete -e 'ssh -i deployment.key' --chmod=u=rwX,g=rX _book/ timroes@rsync.keycdn.com:zones/a11ybook/
